require("plugins")
require("theme")
require("settings")
require("keymaps")
require("treesitter")
require("cmp-settings")
require("lsp")
require("lsp.keymaps")
require("status")
require("neogit-settings")
-- require("fugitive")
require("telescope-settings")
require("quickscope")
