require("plugins")
require("theme")
require("settings")
require("keymaps")
require("treesitter")
require("org-settings")
require("cmp-settings")
require("lsp")
require("lsp.keymaps")
require("status")
require("git-settings")
require("telescope-settings")
-- require("neoformat-settings")
require("hop-settings")
