require("gitsigns").setup()
local map = require("utils").map

map("n", "<leader>gs", ":G<CR>", { silent = true })
map("n", "<leader>gd", ":Gdiff<CR>", { silent = true })
map("n", "<leader>gb", ":Gblame<CR>", { silent = true })
map("n", "<leader>gP", ":G push<CR>", { silent = true, nowait = true })
map("n", "<leader>gp", ":G pull<CR>", { silent = true, nowait = true })
map("n", "<leader>cvc", ":G commit --verbose<CR>", { silent = true })
map("n", "<leader>us", ":Gitsigns stage_hunk<CR>", { silent = true })
map("n", "<leader>ur", ":Gitsigns reset_hunk<CR>", { silent = true })
map("v", "<leader>us", ":Gitsigns stage_hunk<CR>", { silent = true })
map("n", "<leader>uS", ":Gitsigns stage_buffer<CR>", { silent = true })
map("n", "<leader>uu", ":Gitsigns undo_stage_hunk<CR>", { silent = true })
map("n", "<leader>uR", ":Gitsigns reset_buffer<CR>", { silent = true })
map("n", "<leader>up", ":Gitsigns preview_hunk<CR>", { silent = true })
map("n", "<leader>ub", ":Gitsigns blame_line<CR>", { silent = true })
map("n", "<leader>ud", ":Gitsigns diffthis<CR>", { silent = true })
map("n", "<leader>tb", ":Gitsigns toggle_current_line_blame<CR>", { silent = true })
map("n", "<leader>hd", ":Gitsigns diffthis<CR>", { silent = true })
map("n", "<leader>td", ":Gitsigns toggle_deleted<CR>", { silent = true })
map("n", "]c", ":Gitsigns next_hunk<CR>", { silent = true })
map("n", "[c", ":Gitsigns prev_hunk<CR>", { silent = true })
